default: ec2_yum_linux
ec2_yum_linux:
    cloud: ec2
    distro: redhat
    provisioner: yum
    volume: linux
    blockdevice: linux
    finalizer: tagging_ebs
ec2_apt_linux:
    cloud: ec2
    distro: debian
    provisioner: apt
    volume: linux
    blockdevice: linux
    finalizer: tagging_ebs
ec2_aptitude_linux:
    cloud: ec2
    distro: debian
    provisioner: aptitude
    volume: linux
    blockdevice: linux
    finalizer: tagging_ebs
ec2_yum_linux_s3:
    cloud: ec2
    distro: redhat
    provisioner: yum
    volume: linux
    blockdevice: linux
    finalizer: tagging_s3
ec2_apt_linux_s3:
    cloud: ec2
    distro: debian
    provisioner: apt
    volume: linux
    blockdevice: linux
    finalizer: tagging_s3
ec2_aptitude_linux_s3:
    cloud: ec2
    distro: debian
    provisioner: aptitude
    volume: linux
    blockdevice: linux
    finalizer: tagging_s3
docker_yum:
    cloud: docker
    distro: redhat
    provisioner: yum
    volume: docker
    blockdevice: "null"
    finalizer: docker
docker_apt:
    cloud: docker
    distro: debian
    provisioner: apt
    volume: docker
    blockdevice: "null"
    finalizer: docker
docker_aptitude:
    cloud: docker
    distro: debian
    provisioner: aptitude
    volume: docker
    blockdevice: "null"
    finalizer: docker
