default: ec2_yum_linux
ec2_yum_linux:
    cloud: ec2
    provisioner: yum
    volume: linux
    blockdevice: linux
    finalizer: tagging
ec2_apt_linux:
    cloud: ec2
    provisioner: apt
    volume: linux
    blockdevice: linux
    finalizer: tagging
