version: 1
formatters:
  simple:
    format: '%(asctime)s [%(levelname)s] %(message)s'
    datefmt: '%F %T'
  detailed:
    format: '%(asctime)s [%(levelname)s] [%(filename)s(%(lineno)s):%(funcName)s] %(message)s'
    datefmt: '%F %T'
handlers:
  console:
    class: logging.StreamHandler
    formatter: simple
    level: INFO
    stream: ext://sys.stdout
  per_package_file:
    class: logging.FileHandler
    formatter: detailed
    level: DEBUG
    filename_format: '/var/log/aminator/per_package/{0[package]}-{0[now]:%Y%m%d%H%M}.log' 
  main_file:
    class: logging.handlers.TimedRotatingFileHandler
    formatter: detailed
    level: DEBUG
    filename: /var/log/aminator/aminator.log
    when: 'midnight'
    backupCount: 7
    utc: True
loggers:
  aminator:
    level: DEBUG
    handlers: [console, main_file, per_package_file]
