# each dict will be pulled in and set up with dictConfig. Obey the dictConfig schema.
base:
  enabled: true
  config:
    version: 1
    disable_existing_loggers: false
    formatters:
      simple:
        format: '%(asctime)s [%(levelname)s] %(message)s'
        datefmt: '%F %T'
      detailed:
        format: '%(asctime)s [%(levelname)s] [%(name)s(%(lineno)s):%(funcName)s] %(message)s'
        datefmt: '%F %T'
    handlers:
      console:
        class: logging.StreamHandler
        formatter: simple
        level: INFO
        stream: ext://sys.stdout
      per_package:
        class: logging.FileHandler
        filename: /dev/null
        formatter: detailed
        level: DEBUG
      boto:
        class: logging.FileHandler
        filename: /dev/null
        formatter: detailed
        level: DEBUG
    root:
      handlers: [console, per_package, boto]
per_package:
  enabled: true
  filename_format: '{0}-{1:%Y%m%d%H%M}.log'
boto:
  enabled: false
  filename_format: 'boto-{0}-{1:%Y%m%d%H%M}.log'
